version: '3.1'

services:
  dbLocal:
    container_name: LocalDb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - 5432:5432
    volumes:
      - ./.pgdata:/var/lib/postgresql/data